config/routes.rb
Rails.application.routes.draw do

  resources :cats

  resources :cat_rental_requests do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root 'cats#index'

end

app/models/cat.rb
class Cat < ActiveRecord::Base

  validates :age, :name, :sex, presence: true
  validates :age, numericality: true
  validates :sex, inclusion: { in: %w(M F) }

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    :dependent => :destroy
  )


end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  before_validation :set_status

  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }

  belongs_to :cat

  def approve!
    raise "An overlapping APPROVED request exists." unless overlapping_approved_requests.empty?
    self.class.transaction do
      update(status: "APPROVED")
      overlapping_pending_requests.each do |request|
        request.update(status: "DENIED")
      end
    end
  end

  def deny!
    update(status: "DENIED")
  end

  def overlapping_requests
    sql_params = {
      cat_id: cat_id,
      start_date: start_date,
      end_date: end_date,
      id: id
    }
    CatRentalRequest.select("*").where(<<-SQL, sql_params)
      id != :id
    AND
      cat_id = :cat_id
    AND
      (start_date BETWEEN :start_date AND :end_date
      OR
      end_date BETWEEN :start_date AND :end_date)
    SQL
  end

  def overlapping_pending_requests
    sql_params = {
      cat_id: cat_id,
      start_date: start_date,
      end_date: end_date,
      id: id,
      status: "PENDING"
    }
    CatRentalRequest.select("*").where(<<-SQL, sql_params)
      id != :id
    AND
      cat_id = :cat_id
    AND
      status = :status
    AND
      (start_date BETWEEN :start_date AND :end_date
      OR
      end_date BETWEEN :start_date AND :end_date)
    SQL
  end

  def overlapping_approved_requests
    sql_params = {
      cat_id: cat_id,
      start_date: start_date,
      end_date: end_date,
      id: id,
      status: "APPROVED"
    }
    CatRentalRequest.select("*").where(<<-SQL, sql_params)
      id != :id
    AND
      cat_id = :cat_id
    AND
      status = :status
    AND
      (start_date BETWEEN :start_date AND :end_date
      OR
      end_date BETWEEN :start_date AND :end_date)
    SQL
  end

  private

    def set_status
      self.status ||= "PENDING"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @requests = CatRentalRequest.all
  end

  def show
    @request = CatRentalRequest.find(params[:id])
  end

  def new
    @request = CatRentalRequest.new()
    @cats = Cat.all
  end

  def edit
    @request = CatRentalRequest.find(params[:id])
    @cats = Cat.all
  end

  def update
    @request = CatRentalRequest.find(params[:id])
    if @request.valid?
      @request.update(request_params)
      redirect_to cat_url(@request.cat)
    else
      @request.errors.full_messages
    end
  end

  def create
    @request = CatRentalRequest.new(request_params)
    if @request.valid?
      @request.save!
      redirect_to cat_url(@request.cat)
    else
      @request.errors.full_messages
    end
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cat_url(@request.cat)
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cat_url(@request.cat)
  end

  private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new(cat_params)
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.valid?
      @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      @cat.errors.full_messages
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.valid?
      @cat.save!
      redirect_to cat_url(@cat)
    else
      @cat.errors.full_messages
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :color, :age, :birth_date, :sex)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<form action="<%= request.persisted? ? cat_rental_request_url(request) : cat_rental_requests_url %>" method="post">
  <% if request.persisted? %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <table>
    <tr>
      <td><label for="request_cat_id"><strong>Cat ID</strong></label></td>

      <td>
        <select name="cat_rental_request[cat_id]" id="request_cat_id">
          <option></option>
          <% cats.each do |cat_to_request| %>
            <option value="<%= cat_to_request.id %>" <% if request.persisted? && request.cat.id == cat_to_request.id %> selected <% end %>>
              <%= cat_to_request.id %>
            </option>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td><label for="request_start_date"><strong>Start Date</strong></label></td>
      <td>
        <input type="date" name="cat_rental_request[start_date]" value="<%= request.start_date %>" id="request_start_date">
      </td>
    </tr>
    <tr>
      <td><label for="request_end_date"><strong>End Date</strong></label></td>
      <td>
        <input type="date" name="cat_rental_request[end_date]" value="<%= request.end_date %>" id="request_end_date">
      </td>
    </tr>
    <% if request.persisted? %>
    <tr>
      <td><label for="request_status"><strong>Status</strong></label></td>
      <td>
        <select name="cat_rental_request[status]" id="request_status">
          <option value="PENDING" <% if request.status == "PENDING" %> selected <% end %>>PENDING</option>
          <option value="APPROVED" <% if request.status == "APPROVED" %> selected <% end %>>APPROVED</option>
          <option value="DENIED" <% if request.status == "DENIED" %> selected <% end %>>DENIED</option>
        </select>
      </td>
    </tr>
    <% end %>
  </table>
  <input type="submit" value="Create Cat Rental Request">

</form>

app/views/cat_rental_requests/edit.html.erb
<h1 id="edit_request">Edit Your Cat Rental Request</h1>
<div id="request_form">
  <%= render partial: 'form', locals: { request: @request, cats: @cats } %>
</div>

app/views/cat_rental_requests/new.html.erb
<h1 id="new_request">New Cat Rental Request</h1>
<div id="request_form">
  <%= render partial: 'form', locals: { request: @request, cats: @cats } %>
</div>

app/views/cats/_cat.html.erb
<h3><%= cat.name %></h3>
<table>
  <tr>
    <td><%= cat.color %></td>
    <td><%= cat.sex %></td>
  </tr>
</table>

app/views/cats/_cat_rental.html.erb
<h3><%= link_to "Request ID: #{request.id}", edit_cat_rental_request_url(request) %></h3>
<p><%= request.start_date %> to <%= request.end_date %></p>
<p><%= request.status %></p>
<% if request.status == "PENDING" %>
  <%= button_to [:approve, request] do %>Approve<% end %>
  <%= button_to [:deny, request] do %>Deny<% end %>
<% end %>

app/views/cats/_form.html.erb
<form action="<%= cat.persisted? ? cat_url(cat) : cats_url %>" method="post">
  <% if cat.persisted? %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <table>
    <tr>
      <td><label for="cat_name"><strong>Name</strong></label></td>
      <td><input type="text" name="cat[name]" id="cat_name" value="<%= cat.name %>"></td>
    </tr>
    <tr>
      <td><label for="cat_age"><strong>Age</strong></label></td>
      <td><input type="text" name="cat[age]" id="cat_age" value="<%= cat.age %>"></td>
    </tr>
    <tr>
      <td><strong>Sex</strong></td>
      <td></td>
    </tr>
    <tr>
      <td><input type="radio" name="cat[sex]" id="cat_sex_female" value="F"
        <% if cat.sex == "F" %> checked=1 <% end %>></td>
      <td><label for="cat_sex_female">Female</label></td>
    </tr>
    <tr>
      <td><input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
        <% if cat.sex == "M" %> checked=1 <% end %>>
</td>
      <td><label for="cat_sex_male">Male</label></td>
    </tr>
    <tr>
      <td><label for="cat_color"><strong>Color</strong></label></td>

      <td>
        <select name="cat[color]" id="cat_color">
          <option></option>
          <option value="brown" <% if cat.color == "brown" %> selected <% end %>>Brown</option>
          <option value="black" <% if cat.color == "black" %> selected <% end %>>Black</option>
          <option value="blue" <% if cat.color == "blue" %> selected <% end %>>Blue</option>
          <option value="white" <% if cat.color == "white" %> selected <% end %>>White</option>
          <option value="orange" <% if cat.color == "orange" %> selected <% end %>>Orange</option>
          <option value="tabby" <% if cat.color == "tabby" %> selected <% end %>>Tabby</option>
        </select>
      </td>
    </tr>
    <tr>
      <td><label for="cat_birth_date"><strong>Birth Date</strong></label></td>

      <td>
        <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>" id="cat_birth_date">
      </td>

    </tr>
  </table>
  <input type="submit" value="Create Cat">

</form>

app/views/cats/edit.html.erb
<h1 id="edit_cat">Edit <%= @cat.name %>'s Information</h1>
<div id="cat_form">
  <%= render partial: 'form', locals: { cat: @cat } %>
</div>

app/views/cats/index.html.erb
<h1 id="cats">Cats</h1>
<% @cats.each do |cat| %>

<div><%= render partial: 'cat', locals: {cat: cat} %></div>

<% end %>

app/views/cats/new.html.erb
<form action="<%= new_cat_url %>" method="post">
  <table>
    <tr>
      <td><label for="cat_name"><strong>Name</strong></label></td>
      <td><input type="text" name="cat[name]" id="cat_name"></td>
    </tr>
    <tr>
      <td><label for="cat_age"><strong>Age</strong></label></td>
      <td><input type="text" name="cat[age]" id="cat_age"></td>
    </tr>
    <tr>
      <td><strong>Sex</strong></td>
      <td></td>
    </tr>
    <tr>
      <td><input type="radio" name="cat[sex]" id="cat_sex_female" value="F"></td>
      <td><label for="cat_sex_female">Female</label></td>
    </tr>
    <tr>
      <td><input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
</td>
      <td><label for="cat_sex_male">Male</label></td>
    </tr>
    <tr>
      <td><label for="cat_color"><strong>Color</strong></label></td>

      <td>
        <select name="cat[coat_color]" id="cat_coat_color">
          <option></option>
          <option value="brown">Brown</option>
          <option value="black">Black</option>
          <option value="blue">Blue</option>
          <option value="white">White</option>
          <option value="orange">Orange</option>
        </select>
      </td>

    </tr>
    <tr>
      <td><label for="cat_birth_date"><strong>Birth Date</strong></label></td>

      <td>
        <input type="date" name="cat[birth_date]" value="" id="cat_birth_date">
      </td>

    </tr>
  </table>
  <input type="submit" value="Create Cat">

</form>

app/views/cats/show.html.erb
<h3><%= @cat.name %></h3>
<table>
  <tr>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
  </tr>
</table>
<p>Rental Requests: <%= @cat.rental_requests.count %></p>
<div>
  <% @cat.rental_requests.order(:start_date).each do |request| %>
    <%= render partial: "cat_rental", locals: {request: request} %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>99Cats</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>